version: '3.8'

services:
  cron-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cron-service
    environment:
      SECRET_TOKEN: "${SECRET_TOKEN}"
    networks:
      - digital_network
    volumes:
      - ./scripts:/scripts
      - ./logs:/var/log
    restart: unless-stopped

networks:
  digital_network:
    driver: bridge