version: '3.8'

services:
  cron-service:
    build:
      context: ./cron-service
      dockerfile: Dockerfile
    container_name: cron-service
    environment:
      SECRET_TOKEN: "${SECRET_TOKEN}" # Pass secrets securely
    networks:
      - digital_network
    volumes:
      - ./scripts:/scripts # Mount script folder
      - ./logs:/var/log    # Mount logs folder
    restart: unless-stopped

networks:
  digital_network:
    driver: bridge